# Generated by Django 2.2.7 on 2019-11-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfall_app', '0003_auto_20191125_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastupdate',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
