# Generated by Django 2.2.7 on 2019-11-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CESBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('velocity', models.CharField(default='', max_length=100)),
                ('x_pos', models.CharField(default='', max_length=100)),
                ('y_pos', models.CharField(default='', max_length=100)),
                ('z_pos', models.CharField(default='', max_length=101)),
            ],
        ),
        migrations.CreateModel(
            name='KeplerianElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semi_major_axis_diacritic', models.CharField(default='', max_length=100)),
                ('semi_major_axis_subscript', models.CharField(default='', max_length=100)),
                ('eccentricity_diacritic', models.CharField(default='', max_length=100)),
                ('eccentricity_subscript', models.CharField(default='', max_length=100)),
                ('inclination_diacritic', models.CharField(default='', max_length=100)),
                ('inclination_subscript', models.CharField(default='', max_length=100)),
                ('mean_longitude_diacritic', models.CharField(default='', max_length=100)),
                ('mean_longitude_subscript', models.CharField(default='', max_length=100)),
                ('longitude_of_perihelion_diacritic', models.CharField(default='', max_length=100)),
                ('longitude_of_perihelion_subscript', models.CharField(default='', max_length=100)),
                ('longitude_of_the_ascending_node_diacritic', models.CharField(default='', max_length=100)),
                ('longitude_of_the_ascending_node_subscript', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=32)),
                ('x_pos', models.CharField(default='', max_length=100)),
                ('y_pos', models.CharField(default='', max_length=100)),
                ('z_pos', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LastUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('gas_or_rocky', models.CharField(default='', max_length=101)),
                ('photo_url', models.TextField(default='')),
                ('CESBodyData', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Planet', to='skyfall_app.CESBody')),
            ],
        ),
        migrations.CreateModel(
            name='NearEarthObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('orbiting_body', models.CharField(default='', max_length=101)),
                ('photo_url', models.TextField(default='')),
                ('CESBodyData', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='NearEarthObjects', to='skyfall_app.CESBody')),
            ],
        ),
    ]
