# Generated by Django 2.2.7 on 2019-11-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfall_app', '0002_auto_20191125_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesbody',
            name='z_pos',
            field=models.CharField(max_length=101),
        ),
        migrations.AlterField(
            model_name='lastupdate',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
