# Generated by Django 2.2.7 on 2019-11-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CESBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pos', models.CharField(max_length=100)),
                ('y_pos', models.CharField(max_length=100)),
                ('z_pos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeplerianElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semi_major_axis_diacritic', models.CharField(max_length=100)),
                ('semi_major_axis_subscript', models.CharField(max_length=100)),
                ('eccentricity_diacritic', models.CharField(max_length=100)),
                ('eccentricity_subscript', models.CharField(max_length=100)),
                ('inclination_diacritic', models.CharField(max_length=100)),
                ('inclination_subscript', models.CharField(max_length=100)),
                ('mean_longitude_diacritic', models.CharField(max_length=100)),
                ('mean_longitude_subscript', models.CharField(max_length=100)),
                ('longitude_of_perihelion_diacritic', models.CharField(max_length=100)),
                ('longitude_of_perihelion_subscript', models.CharField(max_length=100)),
                ('longitude_of_the_ascending_node_diacritic', models.CharField(max_length=100)),
                ('longitude_of_the_ascending_node_subscript', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=32)),
                ('x_pos', models.CharField(max_length=100)),
                ('y_pos', models.CharField(max_length=100)),
                ('z_pos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LastUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NearEarthObjects',
            fields=[
                ('cesbody_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyfall_app.CESBody')),
            ],
            bases=('skyfall_app.cesbody',),
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('cesbody_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skyfall_app.CESBody')),
            ],
            bases=('skyfall_app.cesbody',),
        ),
    ]
