# Generated by Django 2.2.7 on 2019-11-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyfall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesbody',
            name='description',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='cesbody',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='cesbody',
            name='velocity',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='lastupdate',
            name='date',
            field=models.DateField(default='null'),
        ),
    ]
